# Whether to enable debug messages.
# This will send additional messages to help debug Dreamvisitor.
# Default: false
debug: false

# The Dreamvisitor bot token. DO NOT SHARE THIS.
# Dreamvisitor will not work properly unless this is a valid bot token.
# Ask Bog for a bot token if Dreamvisitor reports a login error on startup.
# Default: BOT_TOKEN
bot-token: BOT_TOKEN

# Website URL
# The URL for the whitelisting website.
# Default: "https://woftnw.duckdns.org"
website-url: "https://woftnw.duckdns.org"

# Whether web whitelisting is enabled or not
# This can be set with the /toggleweb Discord command.
# Default: true
web-whitelist: true

# The channel ID of the game chat.
# This can be set on Discord with /setgamechat
# Default: 880269118975119410
chatChannelID: 880269118975119410

# The channel ID of the log chat.
# This can be set on Discord /setlogchat
# Default: 1114730320068104262
logChannelID: 1114730320068104262

# The channel ID of the whitelist chat.
# This can be set on Discord /setwhitelist
# Default: 858461513991323688
whitelistChannelID: 858461513991323688

# The role IDs of tribes on the main server.
# This can be set on Discord with /setrole
triberoles:
  - 964773117803249694
  - 660599218439716906
  - 964773289203490837
  - 660599477622669312
  - 660599843093348392
  - 660599418344439842
  - 660600003315761172
  - 660599559654735893
  - 964773212321882132
  - 660599708145942581

# Images for each of the tribes.
# Used for the royalty board and log messages.
tribe-emblems:
  - https://cdn.discordapp.com/emojis/1059550841939431434.webp?size=44&quality=lossless
  - https://cdn.discordapp.com/emojis/848783045960269855.webp?size=44&quality=lossless
  - https://cdn.discordapp.com/emojis/1059550991025971342.webp?size=44&quality=lossless
  - https://cdn.discordapp.com/emojis/848783194912587798.webp?size=44&quality=lossless
  - https://cdn.discordapp.com/emojis/848782864060514395.webp?size=44&quality=lossless
  - https://cdn.discordapp.com/emojis/848783641080233984.webp?size=44&quality=lossless
  - https://cdn.discordapp.com/emojis/848781744315826196.webp?size=44&quality=lossless
  - https://cdn.discordapp.com/emojis/848783311815573554.webp?size=44&quality=lossless
  - https://cdn.discordapp.com/emojis/1059550024704463019.webp?size=44&quality=lossless
  - https://cdn.discordapp.com/emojis/848781745038163978.webp?size=44&quality=lossless

# Whether chat is paused or not.
# This can be toggled in Minecraft with /pausechat
# Default: false
chatPaused: false

# Whether the soft whitelist is enabled or not
# This can be set in Minecraft with /softwhitelist [on|off]
# Default: false
softwhitelist: false

# Player limit override. This will override the player limit, both over and under.
# This can be set in Minecraft with /playerlimit <int>
# Default: -1
playerlimit: -1

# Whether to globally disable pvp or not.
# This can be toggled in Minecraft with /togglepvp
# Default: false
disablepvp: false

# The location of the recorded hub.
# This can be set in Minecraft with /sethub
# Default: none
hubLocation: none

# Whether to copy the output of the console to the Discord log channel.
# This will disable the default Dreamvisitor logging in place of the Minecraft server console.
# Default: false
log-console: false

# Whether to pass messages in the log channel as console commands.
# If log-console is enabled, this will take messages sent by users with the Discord administrator permission and pass
#   them as console commands.
# Default: false
enable-log-console-commands: false

# The amount of time in days (as an integer) that infractions take to expire.
# Expired infractions are not deleted, but they do not count toward a total infraction count.
# Default: 90
infraction-expire-time-days: 90

# The ID of the category to create infractions channels.
# They will accumulate here.
# Default: 1226180189604544593
infractions-category-id: 1226180189604544593

# The name of the Discord shop.
# This will appear at the top of the embed.
# Default: "Shop"
shopName: "Shop"

# The icon used for currency in the Discord economy system.
# This can be any string, including symbols, letters, emojis, and Discord custom emoji.
# Default: "$"
currencyIcon: "$"

# The base amount given by the /daily Discord command.
# This is the default amount before adding the streak bonus. The total amount is decided by dailyBaseAmount + (user's streak * this).
# Default: 10.00
dailyBaseAmount: 10.00

# The multiplier of the streak bonus given by the /daily command.
# This is multiplied by the streak and added to the base amount. The total amount is decided by dailyBaseAmount + (user's streak * this).
# Default: 5.00
dailyStreakMultiplier: 5.00

# The amount gained from the /work command.
# /work can only be run every hour.
# Default: 20.00
workReward: 20.00

# The multiplier of the distance weight when choosing mail delivery locations.
# Takes the ratio (between 0 and 1) of the distance to the maximum distance between locations,
#   multiplies it by this value, and adds it to the mail location weight.
# This weight is used to randomly choose a mail location to deliver to in order to provide a realistic
#   relationship between delivery locations.
# At 0, distance has no effect on location selection.
# At 1, the weight will have slight effect on the location selection.
# At 10, the weight will have significant effect on the location selection.
# The weight is applied inversely, making closer distances worth more than further distances.
# Default: 1.00
mailDeliveryLocationSelectionDistanceWeightMultiplier: 1.00

# Mail delivery reward is calculated by multiplying the distance by this number.
# The result is then rounded to the nearest ten.
# At 0, the reward given is 0.
# At 1, the reward given will be the distance in blocks.
# Default: 0.05
mailDistanceToRewardMultiplier: 0.05